version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached
      - ${TWS_DEPLOY_DIR}:/build
    
    command: sleep infinity
    networks:
      - "loc-net"
      - "mongo-net"
    environment: 
      - MONGODB_STRING=mongodb://user:user@mongodb

  mongodb:
    image: mongo:5
    volumes:
      - mongodata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=user
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_DATABASE=travel
    networks:
      - "mongo-net"
volumes:
  mongodata:
networks:
  loc-net:
    name: verdaccio-local-net
    external: true
  mongo-net: